/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GamesRouteImport } from './routes/games'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as HostRouteImport } from './routes/host'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as BookVenueIdRouteImport } from './routes/book.$venueId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as GroupsCreateRouteImport } from './routes/groups.create'
import { Route as VenuesIndexRouteImport } from './routes/venues.index'
import { Route as VenuesVenueIdRouteImport } from './routes/venues.$venueId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVenueIdRoute = BookVenueIdRouteImport.update({
  id: '/book/$venueId',
  path: '/book/$venueId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => GamesRoute,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => GroupsRoute,
} as any)
const GroupsCreateRoute = GroupsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => GroupsRoute,
} as any)
const VenuesIndexRoute = VenuesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VenuesRoute,
} as any)
const VenuesVenueIdRoute = VenuesVenueIdRouteImport.update({
  id: '/$venueId',
  path: '/$venueId',
  getParentRoute: () => VenuesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/events': typeof EventsRouteWithChildren
  '/games': typeof GamesRouteWithChildren
  '/groups': typeof GroupsRouteWithChildren
  '/host': typeof HostRoute
  '/invite': typeof InviteRoute
  '/profile': typeof ProfileRoute
  '/venues': typeof VenuesRouteWithChildren
  '/book/$venueId': typeof BookVenueIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/create': typeof GroupsCreateRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/venues/': typeof VenuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/events': typeof EventsRouteWithChildren
  '/games': typeof GamesRouteWithChildren
  '/groups': typeof GroupsRouteWithChildren
  '/host': typeof HostRoute
  '/invite': typeof InviteRoute
  '/profile': typeof ProfileRoute
  '/book/$venueId': typeof BookVenueIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/create': typeof GroupsCreateRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/venues': typeof VenuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/events': typeof EventsRouteWithChildren
  '/games': typeof GamesRouteWithChildren
  '/groups': typeof GroupsRouteWithChildren
  '/host': typeof HostRoute
  '/invite': typeof InviteRoute
  '/profile': typeof ProfileRoute
  '/venues': typeof VenuesRouteWithChildren
  '/book/$venueId': typeof BookVenueIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/create': typeof GroupsCreateRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/venues/': typeof VenuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bookings'
    | '/events'
    | '/games'
    | '/groups'
    | '/host'
    | '/invite'
    | '/profile'
    | '/venues'
    | '/book/$venueId'
    | '/events/$eventId'
    | '/games/$gameId'
    | '/groups/$groupId'
    | '/groups/create'
    | '/venues/$venueId'
    | '/venues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookings'
    | '/events'
    | '/games'
    | '/groups'
    | '/host'
    | '/invite'
    | '/profile'
    | '/book/$venueId'
    | '/events/$eventId'
    | '/games/$gameId'
    | '/groups/$groupId'
    | '/groups/create'
    | '/venues/$venueId'
    | '/venues'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bookings'
    | '/events'
    | '/games'
    | '/groups'
    | '/host'
    | '/invite'
    | '/profile'
    | '/venues'
    | '/book/$venueId'
    | '/events/$eventId'
    | '/games/$gameId'
    | '/groups/$groupId'
    | '/groups/create'
    | '/venues/$venueId'
    | '/venues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  EventsRoute: typeof EventsRouteWithChildren
  GamesRoute: typeof GamesRouteWithChildren
  GroupsRoute: typeof GroupsRouteWithChildren
  HostRoute: typeof HostRoute
  InviteRoute: typeof InviteRoute
  ProfileRoute: typeof ProfileRoute
  VenuesRoute: typeof VenuesRouteWithChildren
  BookVenueIdRoute: typeof BookVenueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$venueId': {
      id: '/book/$venueId'
      path: '/book/$venueId'
      fullPath: '/book/$venueId'
      preLoaderRoute: typeof BookVenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof GamesRoute
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/groups/create': {
      id: '/groups/create'
      path: '/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof GroupsCreateRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/venues/': {
      id: '/venues/'
      path: '/'
      fullPath: '/venues/'
      preLoaderRoute: typeof VenuesIndexRouteImport
      parentRoute: typeof VenuesRoute
    }
    '/venues/$venueId': {
      id: '/venues/$venueId'
      path: '/$venueId'
      fullPath: '/venues/$venueId'
      preLoaderRoute: typeof VenuesVenueIdRouteImport
      parentRoute: typeof VenuesRoute
    }
  }
}

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface GamesRouteChildren {
  GamesGameIdRoute: typeof GamesGameIdRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesGameIdRoute: GamesGameIdRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface GroupsRouteChildren {
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupsCreateRoute: typeof GroupsCreateRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupsCreateRoute: GroupsCreateRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

interface VenuesRouteChildren {
  VenuesVenueIdRoute: typeof VenuesVenueIdRoute
  VenuesIndexRoute: typeof VenuesIndexRoute
}

const VenuesRouteChildren: VenuesRouteChildren = {
  VenuesVenueIdRoute: VenuesVenueIdRoute,
  VenuesIndexRoute: VenuesIndexRoute,
}

const VenuesRouteWithChildren =
  VenuesRoute._addFileChildren(VenuesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  EventsRoute: EventsRouteWithChildren,
  GamesRoute: GamesRouteWithChildren,
  GroupsRoute: GroupsRouteWithChildren,
  HostRoute: HostRoute,
  InviteRoute: InviteRoute,
  ProfileRoute: ProfileRoute,
  VenuesRoute: VenuesRouteWithChildren,
  BookVenueIdRoute: BookVenueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
